In [2]:
import numpy as np

In [3]:
#Create a 5x5 array
array_aarav = np.array([[1,2,3,4,5],
                       [6,7,8,10,11],
                       [12,13,14,15,16],
                       [17,18,19,20,21],
                       [22,23,24,25,26]])

In [4]:
print(array_aarav)

[[ 1  2  3  4  5]
 [ 6  7  8 10 11]
 [12 13 14 15 16]
 [17 18 19 20 21]
 [22 23 24 25 26]]


In [5]:
print(array_aarav[4])

[22 23 24 25 26]


In [6]:
array_aarav[4,:]

array([22, 23, 24, 25, 26])

In [7]:
array_aarav[:,3]

array([ 4, 10, 15, 20, 25])

In [8]:
#Array Slicing
array_slicing = np.arange(10,41)

In [9]:
array_slicing

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40])

In [10]:
array_slicing[3::2]

array([13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39])

In [11]:
#2D Array Slicing
array_2d_slicing = np.arange(30).reshape(6,5)

In [12]:
array_2d_slicing

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [66]:
array_2d_slicing[0:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [67]:
#array operators
array_operators = np.arange(1,20)

In [71]:
array_operators

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [72]:
array_operators[(array_operators <=6) & (array_operators >= 4)]

array([4, 5, 6])